### ISSUE TITLE
Release new versions?

### ISSUE THREAD

**Issue by apfelbox** [dprint/dprint-plugin-prettier#81] opened 2024-07-16 14:06 UTC
Hi,

there are now new versions released, as the pipeline always fails: https://github.com/dprint/dprint-plugin-prettier/actions/workflows/ci.yml

Thanks
Jannik

**Comment by dsherret** [comment] 2024-07-28 19:06
Sorry, I didn't notice. This is fixed now by https://github.com/dprint/dprint-plugin-prettier/pull/82

Caused by GH changing the definition of macos-latest on GH actions.

**Closed by dsherret** 2024-07-28 19:06 UTC
